using System;
using System.Collections.Generic;
using System.Globalization;

namespace Tapster;

public static class LocalizationManager
{
    public const string LangAuto = "auto";
    public const string LangZhTw = "zh-TW";
    public const string LangEnUs = "en-US";
    public const string LangJaJp = "ja-JP";
    public const string LangZhCn = "zh-CN";

    public static readonly IReadOnlyList<(string Code, string DisplayName)> SupportedLanguages = new[]
    {
        (LangAuto, "跟隨系統 / System Default"),
        (LangZhTw, "繁體中文"),
        (LangEnUs, "English"),
        (LangJaJp, "日本語"),
        (LangZhCn, "简体中文"),
    };

    private static string _currentLanguage = LangAuto;
    private static string _effectiveLanguage = LangEnUs;

    public static event Action? LanguageChanged;

    static LocalizationManager()
    {
        SetLanguage(LangAuto);
    }

    public static string CurrentLanguage => _currentLanguage;
    public static string EffectiveLanguage => _effectiveLanguage;

    public static void SetLanguage(string langCode)
    {
        _currentLanguage = string.IsNullOrWhiteSpace(langCode) ? LangAuto : langCode;

        if (string.Equals(_currentLanguage, LangAuto, StringComparison.OrdinalIgnoreCase))
        {
            _effectiveLanguage = ResolveSystemLanguage();
        }
        else
        {
            _effectiveLanguage = NormalizeLanguageCode(_currentLanguage);
        }

        LanguageChanged?.Invoke();
    }

    private static string ResolveSystemLanguage()
    {
        var currentCulture = CultureInfo.CurrentUICulture.Name;
        if (currentCulture.StartsWith("zh", StringComparison.OrdinalIgnoreCase))
        {
            if (currentCulture.Contains("TW", StringComparison.OrdinalIgnoreCase) ||
                currentCulture.Contains("HK", StringComparison.OrdinalIgnoreCase) ||
                currentCulture.Contains("MO", StringComparison.OrdinalIgnoreCase) ||
                currentCulture.Contains("Hant", StringComparison.OrdinalIgnoreCase))
            {
                return LangZhTw;
            }
            return LangZhCn;
        }

        if (currentCulture.StartsWith("ja", StringComparison.OrdinalIgnoreCase))
        {
            return LangJaJp;
        }

        return LangEnUs;
    }

    private static string NormalizeLanguageCode(string code)
    {
        if (code.StartsWith("zh-TW", StringComparison.OrdinalIgnoreCase) ||
            code.StartsWith("zh-HK", StringComparison.OrdinalIgnoreCase) ||
            code.StartsWith("zh-Hant", StringComparison.OrdinalIgnoreCase))
        {
            return LangZhTw;
        }

        if (code.StartsWith("zh", StringComparison.OrdinalIgnoreCase))
        {
            return LangZhCn;
        }

        if (code.StartsWith("ja", StringComparison.OrdinalIgnoreCase))
        {
            return LangJaJp;
        }

        return LangEnUs;
    }

    public static string Get(string key)
    {
        if (Translations.TryGetValue(_effectiveLanguage, out var dict) && dict.TryGetValue(key, out var val))
        {
            return val;
        }

        if (Translations.TryGetValue(LangEnUs, out var fallbackDict) && fallbackDict.TryGetValue(key, out var fallbackVal))
        {
            return fallbackVal;
        }

        return key;
    }

    public static readonly Dictionary<string, Dictionary<string, string>> Translations = new(StringComparer.OrdinalIgnoreCase)
    {
        [LangZhTw] = new(StringComparer.OrdinalIgnoreCase)
        {
            // Navigation
            ["Nav_Typer"] = "打字",
            ["Nav_Holder"] = "長按",
            ["Nav_Clicker"] = "連點",
            ["Nav_Macro"] = "重放",
            ["Nav_About"] = "關於",
            ["Nav_Settings"] = "設定",

            // Tray Menu
            ["Tray_ShowHide"] = "顯示 / 隱藏 Tapster",
            ["Tray_AlwaysOnTop"] = "視窗永遠置頂",
            ["Tray_Exit"] = "結束 Tapster",
            ["Tray_Tooltip"] = "Tapster (Ctrl+Alt+T 喚醒)",

            // Common Actions & Status
            ["Common_Ready"] = "就緒",
            ["Common_Running"] = "執行中...",
            ["Common_StartingIn"] = "{0} 秒後啟動... 請切換至目標應用程式！",
            ["Common_Stop"] = "停止",
            ["Common_Start"] = "開始",
            ["Common_Delay"] = "延遲 (秒)：",
            ["Common_Finished"] = "執行完成",
            ["Common_StoppedByUser"] = "使用者已手動停止",
            ["Common_TaskCanceled"] = "工作已取消",
            ["Common_EmergencyStop"] = "已透過 F10 緊急熱鍵終止所有工作",
            ["Common_SwitchedTask"] = "已從 {0} 切換工作",
            ["Common_Error"] = "錯誤：{0}",
            ["Common_Save"] = "儲存",
            ["Common_Cancel"] = "取消",

            // Typer Panel
            ["Typer_Title"] = "自動打字機",
            ["Typer_Desc"] = "自動模擬鍵盤輸入指定文字或程式碼，支援遠端桌面與主機終端",
            ["Typer_TargetText"] = "目標文字：",
            ["Typer_PasteBtn"] = "貼上",
            ["Typer_ClearBtn"] = "清除",
            ["Typer_TextPlaceholder"] = "在此輸入要自動輸入的文字內容...",
            ["Typer_ModeLabel"] = "輸入模式：",
            ["Typer_ModeKeystroke"] = "⌨️ 逐字鍵盤模擬",
            ["Typer_ModeClipboard"] = "📋 剪貼簿貼上 (瞬間)",
            ["Typer_ClipboardHint"] = "⚡ 瞬間貼上 (Ctrl+V) 並自動還原剪貼簿原始內容",
            ["Typer_TrailingKeyLabel"] = "結尾按鍵：",
            ["Typer_TrailingNone"] = "無",
            ["Typer_TrailingEnter"] = "Enter (送出 / 換行)",
            ["Typer_TrailingTab"] = "Tab (切換欄位)",
            ["Typer_IntervalLabel"] = "按鍵間隔 (秒/字)：",
            ["Typer_JitterCheck"] = "自然打字微幅抖動 (±15%)",
            ["Typer_HistoryTitle"] = "輸入紀錄",
            ["Typer_ActionStart"] = "開始打字 (F8)",
            ["Typer_ValidationEmpty"] = "請輸入要打字的文字內容",
            ["Typer_PastingClipboard"] = "正在透過剪貼簿貼上 {0} 個字元...",
            ["Typer_PastedClipboard"] = "已貼上 {0} 個字元",
            ["Typer_TypingChar"] = "正在輸入第 {0}/{1} 個字元...",
            ["Typer_PasteError"] = "貼上錯誤：{0}",

            // Key Holder Panel
            ["KeyHolder_Title"] = "按鍵長按",
            ["KeyHolder_Desc"] = "連續按住指定按鍵或組合鍵，支援奔跑、蓄力與按鍵模擬",
            ["KeyHolder_PipelineTitle"] = "按鍵序列管線",
            ["KeyHolder_PipelineHint"] = "• 點擊任意步驟，透過下方鍵盤自訂按鍵組合",
            ["KeyHolder_RepeatTitle"] = "循環次數：",
            ["KeyHolder_AddStepBtn"] = "新增步驟至序列",
            ["KeyHolder_VkTitle"] = "虛擬鍵盤控制器",
            ["KeyHolder_CaptureBtn"] = "擷取實體按鍵",
            ["KeyHolder_CaptureListening"] = "聆聽中...",
            ["KeyHolder_CaptureHint"] = "請按下鍵盤上的任意按鍵...",
            ["KeyHolder_CaptureCanceled"] = "按鍵擷取已取消",
            ["KeyHolder_CaptureSuccess"] = "已擷取按鍵：{0} (步驟 #{1})",
            ["KeyHolder_ClearKeysBtn"] = "清除按鍵",
            ["KeyHolder_Step"] = "步驟 #{0}",
            ["KeyHolder_TapKeysBelow"] = "(點擊下方按鍵)",
            ["KeyHolder_HoldUntilStopped"] = "長按至停止",
            ["KeyHolder_HoldForSeconds"] = "長按 (秒)：",
            ["KeyHolder_RestSeconds"] = "休息 (秒)：",
            ["KeyHolder_MoveUp"] = "上移步驟",
            ["KeyHolder_MoveDown"] = "下移步驟",
            ["KeyHolder_DeleteStep"] = "刪除步驟",
            ["KeyHolder_ActionStart"] = "開始長按 (F7)",
            ["KeyHolder_ValidationNoKeys"] = "請為序列中的步驟設定至少一個按鍵組合",
            ["KeyHolder_EditingStep"] = "(編輯步驟 #{0}: [{1}])",
            ["KeyHolder_NoKeysSet"] = "未設定按鍵",
            ["KeyHolder_KeysClearedForStep"] = "已清除步驟 #{0} 的按鍵",
            ["KeyHolder_PreflightNoKey"] = "請設定要長按的按鍵",
            ["KeyHolder_HoldingDuration"] = "{0}長按 [{1}] ({2:F1}s / {3:F1}s)...",
            ["KeyHolder_HoldingContinuously"] = "{0}持續長按 [{1}] (按停止或 F10 放開)...",
            ["KeyHolder_RestingDuration"] = "{0}休息中 ({1:F1}s / {2:F1}s)...",
            ["KeyHolder_LoopPrefix"] = "[第 {0}/{1} 輪] ",
            ["KeyHolder_LoopInfinitePrefix"] = "[第 {0}/∞ 輪] ",
            ["KeyHolder_StepPrefix"] = "步驟 {0}/{1}：",

            // Clicker Panel
            ["Clicker_Title"] = "滑鼠連點與按鍵連打",
            ["Clicker_Desc"] = "高精度定時滑鼠連點、指定座標鎖定與鍵盤連打工具",
            ["Clicker_TargetTypeLabel"] = "連打目標：",
            ["Clicker_TargetMouse"] = "🖱️ 滑鼠連點",
            ["Clicker_TargetKeyboard"] = "⌨️ 鍵盤連打",
            ["Clicker_TriggerModeLabel"] = "觸發行為：",
            ["Clicker_TriggerToggle"] = "開關切換 (按一下開始/停止)",
            ["Clicker_TriggerHold"] = "按住連打 (按住 F6 連打)",
            ["Clicker_HoldModeHint"] = "💡 按住熱鍵持續連打，放開即刻停止",
            ["Clicker_MouseButtonLabel"] = "點擊按鈕：",
            ["Clicker_MouseLeft"] = "左鍵",
            ["Clicker_MouseRight"] = "右鍵",
            ["Clicker_MouseMiddle"] = "中鍵",
            ["Clicker_SpamKeyLabel"] = "連打按鍵：",
            ["Clicker_SpamKeyPlaceholder"] = "輸入要連打的按鍵 (例：space, f, 1)",
            ["Clicker_IntervalLabel"] = "間隔 (秒)：",
            ["Clicker_CountLabel"] = "連擊次數 (0 = 無限)：",
            ["Clicker_TargetCoordsLabel"] = "目標座標：",
            ["Clicker_PickCoordBtn"] = "鎖定座標",
            ["Clicker_ClearCoordBtn"] = "清除",
            ["Clicker_ShowMarkerCheck"] = "於螢幕顯示準心標記",
            ["Clicker_TimeJitterLabel"] = "時間隨機抖動 (±%)：",
            ["Clicker_TimeJitterCheck"] = "隨機間隔",
            ["Clicker_LocationJitterLabel"] = "位置隨機抖動 (±px)：",
            ["Clicker_LocationJitterHint"] = "像素半徑 (0 = 鎖定精確點)",
            ["Clicker_ActionStart"] = "開始點擊 (F6)",
            ["Clicker_ValidationSpamKey"] = "請輸入要連打的按鍵名稱",
            ["Clicker_PickingCoordsStatus"] = "移動滑鼠至目標位置。按空格/Enter或點擊以鎖定 (Esc 取消)...",
            ["Clicker_PickCoordsCanceled"] = "座標選取已取消",
            ["Clicker_PickCoordsLocked"] = "已鎖定目標座標：({0}, {1})",
            ["Clicker_CoordsCleared"] = "已清除座標 (於目前游標位置點擊)",
            ["Clicker_ClickingCount"] = "點擊中 {0}/{1}...",
            ["Clicker_ClickingInfinite"] = "點擊次數：{0} (無限)...",
            ["Clicker_SpammingKey"] = "連打中 [{0}] {1}/{2}...",
            ["Clicker_SpammingKeyInfinite"] = "連打中 [{0}] 次數：{1} (無限)...",

            // Macro Panel
            ["Macro_Title"] = "動作錄製與重放",
            ["Macro_Desc"] = "錄製滑鼠點擊與鍵盤按鍵動作，並自訂速度重放",
            ["Macro_RecordBtn"] = "開始錄製 (F9)",
            ["Macro_StopRecordBtn"] = "停止錄製",
            ["Macro_ClearBtn"] = "清除動作",
            ["Macro_RepeatLabel"] = "重放次數 (0 = 無限)：",
            ["Macro_SpeedLabel"] = "重放速度倍率：",
            ["Macro_RecordedActionsTitle"] = "已錄製動作 (按兩下步驟可編輯)：",
            ["Macro_EditStepBtn"] = "編輯步驟",
            ["Macro_DeleteStepBtn"] = "刪除步驟",
            ["Macro_ActionsCount"] = "已錄製 {0} 個動作",
            ["Macro_NoActions"] = "尚未錄製任何動作",
            ["Macro_RecordingStatus"] = "正在錄製動作... 點擊或輸入任何內容以進行記錄",
            ["Macro_RecordingCountStatus"] = "正在錄製動作... 已擷取 {0} 個動作 (按停止完成)",
            ["Macro_ClearedStatus"] = "動作已清除",
            ["Macro_ActionReplay"] = "重放動作 (F9)",
            ["Macro_ValidationNoActions"] = "尚未錄製任何動作！請先錄製動作。",
            ["Macro_SelectStepToEdit"] = "請先選擇要編輯的步驟。",
            ["Macro_SelectStepToDelete"] = "請先選擇要刪除的步驟。",
            ["Macro_StepDeleted"] = "已刪除步驟 #{0}",
            ["Macro_StepUpdated"] = "已更新步驟 #{0}",
            ["Macro_ReplayingProgress"] = "重放動作中：第 {0} 輪，動作 {1}/{2}",
            ["Macro_DetailClickLeft"] = "🖱️ 左鍵點擊 ({0}, {1})",
            ["Macro_DetailClickRight"] = "🖱️ 右鍵點擊 ({0}, {1})",
            ["Macro_DetailClickMiddle"] = "🖱️ 中鍵點擊 ({0}, {1})",
            ["Macro_DetailMouseMove"] = "↗️ 移動游標至 ({0}, {1})",
            ["Macro_DetailKeyDown"] = "⌨️ 按下按鍵 [{0}]",
            ["Macro_DetailKeyUp"] = "⌨️ 放開按鍵 [{0}]",
            ["Macro_DetailTypeText"] = "🔤 輸入文字 [{0}]",
            ["Macro_DialogTitle"] = "編輯步驟 #{0}",
            ["Macro_ActionTypeHeader"] = "動作類型：",
            ["Macro_DelayHeader"] = "執行前延遲 (毫秒)：",
            ["Macro_XCoordHeader"] = "X 座標：",
            ["Macro_YCoordHeader"] = "Y 座標：",
            ["Macro_DataHeader"] = "按鍵名稱 / 文字內容：",
            ["Macro_ActionTypeLeftClick"] = "左鍵點擊",
            ["Macro_ActionTypeRightClick"] = "右鍵點擊",
            ["Macro_ActionTypeMiddleClick"] = "中鍵點擊",
            ["Macro_ActionTypeMouseMove"] = "移動游標",
            ["Macro_ActionTypeKeyDown"] = "按下按鍵",
            ["Macro_ActionTypeKeyUp"] = "放開按鍵",
            ["Macro_ActionTypeTypeText"] = "輸入文字",

            // Settings Panel
            ["Settings_Title"] = "偏好設定",
            ["Settings_Desc"] = "自訂 Tapster 系統常駐、開機自動啟動與視窗行為",
            ["Settings_LangTitle"] = "介面語言",
            ["Settings_LangDesc"] = "選擇 Tapster 介面顯示語言，支援即時套用",
            ["Settings_BootTitle"] = "開機自動啟動",
            ["Settings_BootDesc"] = "於 Windows 登入時自動在背景啟動 Tapster 並常駐於系統匣",
            ["Settings_StartMinimizedTitle"] = "啟動時最小化至系統匣",
            ["Settings_StartMinimizedDesc"] = "開啟應用程式時直接隱藏至右下角系統匣，不彈出主視窗干擾",
            ["Settings_CloseToTrayTitle"] = "點擊關閉時縮小至系統匣",
            ["Settings_CloseToTrayDesc"] = "點擊右上角關閉按鈕時縮排至系統匣，保持全域快捷鍵隨叫隨到",
            ["Settings_AlwaysOnTopTitle"] = "視窗永遠置頂",
            ["Settings_AlwaysOnTopDesc"] = "將 Tapster 視窗固定於其他視窗最上層 (全域喚醒熱鍵 Ctrl+Alt+T)",
            ["Settings_HotkeysTitle"] = "全域功能熱鍵",
            ["Settings_HotkeysDesc"] = "即使在遊戲全螢幕或背景視窗，按下熱鍵亦可直接遙控所有功能",
            ["Settings_HkWake"] = "喚醒 / 隱藏主視窗",
            ["Settings_HkClicker"] = "切換連點",
            ["Settings_HkHolder"] = "切換長按",
            ["Settings_HkTyper"] = "啟動打字",
            ["Settings_HkMacro"] = "重放動作",
            ["Settings_HkPanicKill"] = "緊急全部終止",
            ["Settings_HkPanicEscape"] = "緊急中斷跳出",
            ["Settings_AboutNavTitle"] = "版本與專案資訊",
            ["Settings_AboutNavBtn"] = "查看詳情",

            // About Panel
            ["About_Title"] = "關於 Tapster",
            ["About_Desc"] = "應用程式版本、技術規格、專案連結與隱私聲明",
            ["About_HeroSub"] = "Windows 11 原生超輕量自動化助手",
            ["About_HeroSub2"] = "專為遠端桌面 (VNC/RDP)、虛擬機、遊戲掛機與高頻點擊量身打造",
            ["About_SpecsTitle"] = "技術規格",
            ["About_SpecsUiLabel"] = "UI 框架",
            ["About_SpecsCoreLabel"] = "底層自動化核心",
            ["About_SpecsCoreValue"] = "Win32 SendInput 核心 / 微秒級高精調度",
            ["About_SpecsPublishLabel"] = "發布架構",
            ["About_SpecsPublishValue"] = "雙軌制：Microsoft Store MSIX 封裝 + Standalone 綠色純單檔 EXE",
            ["About_SpecsLicenseLabel"] = "授權條款",
            ["About_SpecsLicenseValue"] = "MIT License (100% 免費且開源)",
            ["About_PrivacyTitle"] = "隱私承諾與本地設定",
            ["About_PrivacyDesc"] = "100% 離線純本機運行，零網路遙測傳輸，不收集任何按鍵或個人資料",
            ["About_OpenFolderBtn"] = "開啟設定目錄",
        },

        [LangEnUs] = new(StringComparer.OrdinalIgnoreCase)
        {
            // Navigation
            ["Nav_Typer"] = "Typer",
            ["Nav_Holder"] = "Holder",
            ["Nav_Clicker"] = "Clicker",
            ["Nav_Macro"] = "Replay",
            ["Nav_About"] = "About",
            ["Nav_Settings"] = "Settings",

            // Tray Menu
            ["Tray_ShowHide"] = "Show / Hide Tapster",
            ["Tray_AlwaysOnTop"] = "Always on Top",
            ["Tray_Exit"] = "Exit Tapster",
            ["Tray_Tooltip"] = "Tapster (Ctrl+Alt+T to Wake)",

            // Common Actions & Status
            ["Common_Ready"] = "Ready",
            ["Common_Running"] = "Running...",
            ["Common_StartingIn"] = "Starting in {0}s... Switch to target app!",
            ["Common_Stop"] = "Stop",
            ["Common_Start"] = "Start",
            ["Common_Delay"] = "Delay (s):",
            ["Common_Finished"] = "Finished successfully",
            ["Common_StoppedByUser"] = "Stopped by user",
            ["Common_TaskCanceled"] = "Task canceled",
            ["Common_EmergencyStop"] = "Emergency stop triggered via F10 panic key",
            ["Common_SwitchedTask"] = "Switched task from {0}",
            ["Common_Error"] = "Error: {0}",
            ["Common_Save"] = "Save",
            ["Common_Cancel"] = "Cancel",

            // Typer Panel
            ["Typer_Title"] = "Auto Typer",
            ["Typer_Desc"] = "Simulates keyboard input for VNC, VM consoles, or automated text entry",
            ["Typer_TargetText"] = "Target Text:",
            ["Typer_PasteBtn"] = "Paste",
            ["Typer_ClearBtn"] = "Clear",
            ["Typer_TextPlaceholder"] = "Enter text to automatically type...",
            ["Typer_ModeLabel"] = "Typing Mode:",
            ["Typer_ModeKeystroke"] = "⌨️ Keystroke Emulation",
            ["Typer_ModeClipboard"] = "📋 Clipboard Paste (Instant)",
            ["Typer_ClipboardHint"] = "⚡ Instant paste (Ctrl+V) with clipboard auto-restore",
            ["Typer_TrailingKeyLabel"] = "Trailing Key:",
            ["Typer_TrailingNone"] = "None",
            ["Typer_TrailingEnter"] = "Enter (Send / Newline)",
            ["Typer_TrailingTab"] = "Tab (Switch Field)",
            ["Typer_IntervalLabel"] = "Interval (sec/char):",
            ["Typer_JitterCheck"] = "Natural Typing Jitter (±15%)",
            ["Typer_HistoryTitle"] = "Execution History",
            ["Typer_ActionStart"] = "Start Typer (F8)",
            ["Typer_ValidationEmpty"] = "Please enter text to type",
            ["Typer_PastingClipboard"] = "Pasting {0} chars via clipboard...",
            ["Typer_PastedClipboard"] = "Pasted {0} chars",
            ["Typer_TypingChar"] = "Typing character {0}/{1}...",
            ["Typer_PasteError"] = "Paste error: {0}",

            // Key Holder Panel
            ["KeyHolder_Title"] = "Key Holder",
            ["KeyHolder_Desc"] = "Holds down specified key or key combination continuously",
            ["KeyHolder_PipelineTitle"] = "Key Pipeline Sequence",
            ["KeyHolder_PipelineHint"] = "• Click any step to edit its combo using the keyboard below",
            ["KeyHolder_RepeatTitle"] = "Repeat Loops:",
            ["KeyHolder_AddStepBtn"] = "Add Step to Sequence",
            ["KeyHolder_VkTitle"] = "Virtual Keyboard Controller",
            ["KeyHolder_CaptureBtn"] = "Capture Physical Key",
            ["KeyHolder_CaptureListening"] = "Listening...",
            ["KeyHolder_CaptureHint"] = "Press any key on your keyboard...",
            ["KeyHolder_CaptureCanceled"] = "Key capture canceled",
            ["KeyHolder_CaptureSuccess"] = "Captured key: {0} for Step #{1}",
            ["KeyHolder_ClearKeysBtn"] = "Clear Keys",
            ["KeyHolder_Step"] = "Step #{0}",
            ["KeyHolder_TapKeysBelow"] = "(Tap keys below)",
            ["KeyHolder_HoldUntilStopped"] = "Hold until stopped",
            ["KeyHolder_HoldForSeconds"] = "Hold for (s):",
            ["KeyHolder_RestSeconds"] = "Rest (s):",
            ["KeyHolder_MoveUp"] = "Move step up",
            ["KeyHolder_MoveDown"] = "Move step down",
            ["KeyHolder_DeleteStep"] = "Delete step",
            ["KeyHolder_ActionStart"] = "Start Holder (F7)",
            ["KeyHolder_ValidationNoKeys"] = "Please configure a key combo for the sequence",
            ["KeyHolder_EditingStep"] = "(Editing Step #{0}: [{1}])",
            ["KeyHolder_NoKeysSet"] = "No keys set",
            ["KeyHolder_KeysClearedForStep"] = "Cleared keys for Step #{0}",
            ["KeyHolder_PreflightNoKey"] = "Please enter a key to hold",
            ["KeyHolder_HoldingDuration"] = "{0}Holding [{1}] ({2:F1}s / {3:F1}s)...",
            ["KeyHolder_HoldingContinuously"] = "{0}Holding [{1}] continuously (Press Stop or F10 to release)...",
            ["KeyHolder_RestingDuration"] = "{0}Resting ({1:F1}s / {2:F1}s)...",
            ["KeyHolder_LoopPrefix"] = "[Loop {0}/{1}] ",
            ["KeyHolder_LoopInfinitePrefix"] = "[Loop {0}/∞] ",
            ["KeyHolder_StepPrefix"] = "Step {0}/{1}: ",

            // Clicker Panel
            ["Clicker_Title"] = "Auto Clicker",
            ["Clicker_Desc"] = "Automates mouse clicks with precise interval and coordinate targeting",
            ["Clicker_TargetTypeLabel"] = "Target Type:",
            ["Clicker_TargetMouse"] = "🖱️ Mouse Click",
            ["Clicker_TargetKeyboard"] = "⌨️ Keyboard Spammer",
            ["Clicker_TriggerModeLabel"] = "Trigger Mode:",
            ["Clicker_TriggerToggle"] = "Toggle (Press to Start/Stop)",
            ["Clicker_TriggerHold"] = "Hold to Click (Hold F6)",
            ["Clicker_HoldModeHint"] = "💡 Hold hotkey to spam, release to stop",
            ["Clicker_MouseButtonLabel"] = "Mouse Button:",
            ["Clicker_MouseLeft"] = "Left Click",
            ["Clicker_MouseRight"] = "Right Click",
            ["Clicker_MouseMiddle"] = "Middle Click",
            ["Clicker_SpamKeyLabel"] = "Spam Key / Combo:",
            ["Clicker_SpamKeyPlaceholder"] = "Key to spam (e.g. space, f, 1, e)",
            ["Clicker_IntervalLabel"] = "Interval (sec):",
            ["Clicker_CountLabel"] = "Repeat Count (0 = Infinite):",
            ["Clicker_TargetCoordsLabel"] = "Target Coordinates:",
            ["Clicker_PickCoordBtn"] = "Pick Location",
            ["Clicker_ClearCoordBtn"] = "Clear",
            ["Clicker_ShowMarkerCheck"] = "Show Target Marker on Screen",
            ["Clicker_TimeJitterLabel"] = "Time Jitter (±%):",
            ["Clicker_TimeJitterCheck"] = "Randomize interval",
            ["Clicker_LocationJitterLabel"] = "Location Jitter (±px):",
            ["Clicker_LocationJitterHint"] = "px radius (0 = exact point)",
            ["Clicker_ActionStart"] = "Start Clicker (F6)",
            ["Clicker_ValidationSpamKey"] = "Please enter a key to spam",
            ["Clicker_PickingCoordsStatus"] = "Move cursor to target. Press Space/Enter or click to lock (Esc to cancel)...",
            ["Clicker_PickCoordsCanceled"] = "Coordinate picking canceled",
            ["Clicker_PickCoordsLocked"] = "Locked target coordinates: ({0}, {1})",
            ["Clicker_CoordsCleared"] = "Coordinates cleared (clicking at current cursor location)",
            ["Clicker_ClickingCount"] = "Clicking {0}/{1}...",
            ["Clicker_ClickingInfinite"] = "Clicking count: {0} (Infinite)...",
            ["Clicker_SpammingKey"] = "Spamming [{0}] {1}/{2}...",
            ["Clicker_SpammingKeyInfinite"] = "Spamming [{0}] count: {1} (Infinite)...",

            // Macro Panel
            ["Macro_Title"] = "Action Record & Replay",
            ["Macro_Desc"] = "Record user mouse clicks and keystrokes and replay them back",
            ["Macro_RecordBtn"] = "Start Recording (F9)",
            ["Macro_StopRecordBtn"] = "Stop Recording",
            ["Macro_ClearBtn"] = "Clear Actions",
            ["Macro_RepeatLabel"] = "Replay Loop Count (0 = Infinite):",
            ["Macro_SpeedLabel"] = "Replay Speed Multiplier:",
            ["Macro_RecordedActionsTitle"] = "Recorded Actions (Double-click step to edit):",
            ["Macro_EditStepBtn"] = "Edit Step",
            ["Macro_DeleteStepBtn"] = "Delete Step",
            ["Macro_ActionsCount"] = "{0} actions recorded",
            ["Macro_NoActions"] = "No actions recorded yet",
            ["Macro_RecordingStatus"] = "Recording actions... Click or type anywhere to record actions!",
            ["Macro_RecordingCountStatus"] = "Recording actions... {0} actions captured (Click Stop to finish)",
            ["Macro_ClearedStatus"] = "Actions cleared",
            ["Macro_ActionReplay"] = "Replay Actions (F9)",
            ["Macro_ValidationNoActions"] = "No recorded actions to replay! Please record first.",
            ["Macro_SelectStepToEdit"] = "Please select a step to edit first.",
            ["Macro_SelectStepToDelete"] = "Please select a step to delete first.",
            ["Macro_StepDeleted"] = "Deleted step #{0}",
            ["Macro_StepUpdated"] = "Updated step #{0}",
            ["Macro_ReplayingProgress"] = "Replaying Macro: Loop {0}, Action {1}/{2}",
            ["Macro_DetailClickLeft"] = "🖱️ Left Click at ({0}, {1})",
            ["Macro_DetailClickRight"] = "🖱️ Right Click at ({0}, {1})",
            ["Macro_DetailClickMiddle"] = "🖱️ Middle Click at ({0}, {1})",
            ["Macro_DetailMouseMove"] = "↗️ Move Cursor to ({0}, {1})",
            ["Macro_DetailKeyDown"] = "⌨️ Key Down [{0}]",
            ["Macro_DetailKeyUp"] = "⌨️ Key Up [{0}]",
            ["Macro_DetailTypeText"] = "🔤 Type [{0}]",
            ["Macro_DialogTitle"] = "Edit Step #{0}",
            ["Macro_ActionTypeHeader"] = "Action Type:",
            ["Macro_DelayHeader"] = "Delay Before Action (ms):",
            ["Macro_XCoordHeader"] = "X Coordinate:",
            ["Macro_YCoordHeader"] = "Y Coordinate:",
            ["Macro_DataHeader"] = "Key Name / Text Data:",
            ["Macro_ActionTypeLeftClick"] = "Left Click",
            ["Macro_ActionTypeRightClick"] = "Right Click",
            ["Macro_ActionTypeMiddleClick"] = "Middle Click",
            ["Macro_ActionTypeMouseMove"] = "Move Cursor",
            ["Macro_ActionTypeKeyDown"] = "Key Down",
            ["Macro_ActionTypeKeyUp"] = "Key Up",
            ["Macro_ActionTypeTypeText"] = "Type Text",

            // Settings Panel
            ["Settings_Title"] = "Settings",
            ["Settings_Desc"] = "Preferences, global hotkeys, system tray integration, and appearance",
            ["Settings_LangTitle"] = "Interface Language",
            ["Settings_LangDesc"] = "Choose the display language for Tapster with instant UI updates",
            ["Settings_BootTitle"] = "Start on Windows Boot",
            ["Settings_BootDesc"] = "Automatically launch Tapster in the background when logging into Windows",
            ["Settings_StartMinimizedTitle"] = "Start Minimized to Tray",
            ["Settings_StartMinimizedDesc"] = "Launch directly into the system tray without showing the main window",
            ["Settings_CloseToTrayTitle"] = "Minimize to Tray on Close",
            ["Settings_CloseToTrayDesc"] = "Clicking the close button (X) minimizes to tray instead of quitting",
            ["Settings_AlwaysOnTopTitle"] = "Always on Top",
            ["Settings_AlwaysOnTopDesc"] = "Keep the Tapster window pinned above all other windows (Hotkey: Ctrl+Alt+T)",
            ["Settings_HotkeysTitle"] = "Global Action Hotkeys",
            ["Settings_HotkeysDesc"] = "Control features seamlessly even while running full-screen games or apps",
            ["Settings_HkWake"] = "Wake / Hide Main Window",
            ["Settings_HkClicker"] = "Toggle Clicker",
            ["Settings_HkHolder"] = "Toggle Holder",
            ["Settings_HkTyper"] = "Toggle Typer",
            ["Settings_HkMacro"] = "Replay Actions",
            ["Settings_HkPanicKill"] = "Panic Kill All",
            ["Settings_HkPanicEscape"] = "Panic Escape",
            ["Settings_AboutNavTitle"] = "About & Version Information",
            ["Settings_AboutNavBtn"] = "View Details",

            // About Panel
            ["About_Title"] = "About Tapster",
            ["About_Desc"] = "Application version, technical architecture, and open source links",
            ["About_HeroSub"] = "Windows 11 Native Ultra-Lightweight Automation Utility",
            ["About_HeroSub2"] = "Tailored for remote desktop (VNC/RDP), virtual machines, and high-frequency clicking",
            ["About_SpecsTitle"] = "Technical Specifications",
            ["About_SpecsUiLabel"] = "UI Framework",
            ["About_SpecsCoreLabel"] = "Automation Core",
            ["About_SpecsCoreValue"] = "Win32 SendInput Core / Microsecond Precision Dispatch",
            ["About_SpecsPublishLabel"] = "Distribution",
            ["About_SpecsPublishValue"] = "Dual: Microsoft Store MSIX + Standalone portable single EXE",
            ["About_SpecsLicenseLabel"] = "License",
            ["About_SpecsLicenseValue"] = "MIT License (100% Free & Open Source)",
            ["About_PrivacyTitle"] = "Privacy & Local Data",
            ["About_PrivacyDesc"] = "100% offline local execution, zero network telemetry, no keylogging or data collection",
            ["About_OpenFolderBtn"] = "Open Settings Folder",
        },

        [LangJaJp] = new(StringComparer.OrdinalIgnoreCase)
        {
            // Navigation
            ["Nav_Typer"] = "タイピング",
            ["Nav_Holder"] = "長押し",
            ["Nav_Clicker"] = "連打",
            ["Nav_Macro"] = "再生",
            ["Nav_About"] = "情報",
            ["Nav_Settings"] = "設定",

            // Tray Menu
            ["Tray_ShowHide"] = "Tapsterの表示 / 非表示",
            ["Tray_AlwaysOnTop"] = "常に最前面に表示",
            ["Tray_Exit"] = "Tapsterを終了",
            ["Tray_Tooltip"] = "Tapster (Ctrl+Alt+T で起動)",

            // Common Actions & Status
            ["Common_Ready"] = "待機中",
            ["Common_Running"] = "実行中...",
            ["Common_StartingIn"] = "{0} 秒後に開始... 対象アプリへ切り替えてください！",
            ["Common_Stop"] = "停止",
            ["Common_Start"] = "開始",
            ["Common_Delay"] = "遅延 (秒)：",
            ["Common_Finished"] = "正常に終了しました",
            ["Common_StoppedByUser"] = "ユーザーにより停止されました",
            ["Common_TaskCanceled"] = "タスクがキャンセルされました",
            ["Common_EmergencyStop"] = "F10パニックキーにより緊急停止しました",
            ["Common_SwitchedTask"] = "{0} からタスクを切り替えました",
            ["Common_Error"] = "エラー：{0}",
            ["Common_Save"] = "保存",
            ["Common_Cancel"] = "キャンセル",

            // Typer Panel
            ["Typer_Title"] = "自動タイパー",
            ["Typer_Desc"] = "リモートデスクトップやコンソール向けにテキストを自動キーボード入力",
            ["Typer_TargetText"] = "対象テキスト：",
            ["Typer_PasteBtn"] = "貼り付け",
            ["Typer_ClearBtn"] = "クリア",
            ["Typer_TextPlaceholder"] = "自動入力するテキストを入力してください...",
            ["Typer_ModeLabel"] = "入力モード：",
            ["Typer_ModeKeystroke"] = "⌨️ キーストローク模倣",
            ["Typer_ModeClipboard"] = "📋 クリップボード貼り付け (即時)",
            ["Typer_ClipboardHint"] = "⚡ Ctrl+Vによる即時貼り付け＆クリップボード自動復元",
            ["Typer_TrailingKeyLabel"] = "末尾キー：",
            ["Typer_TrailingNone"] = "なし",
            ["Typer_TrailingEnter"] = "Enter (送信 / 改行)",
            ["Typer_TrailingTab"] = "Tab (フィールド移動)",
            ["Typer_IntervalLabel"] = "キー間隔 (秒/文字)：",
            ["Typer_JitterCheck"] = "自然な打鍵ゆらぎ (±15%)",
            ["Typer_HistoryTitle"] = "実行履歴",
            ["Typer_ActionStart"] = "タイピング開始 (F8)",
            ["Typer_ValidationEmpty"] = "入力するテキストを入力してください",
            ["Typer_PastingClipboard"] = "クリップボード経由で {0} 文字を貼り付け中...",
            ["Typer_PastedClipboard"] = "{0} 文字を貼り付けました",
            ["Typer_TypingChar"] = "{0}/{1} 文字目を入力中...",
            ["Typer_PasteError"] = "貼り付けエラー：{0}",

            // Key Holder Panel
            ["KeyHolder_Title"] = "キーホールド",
            ["KeyHolder_Desc"] = "指定したキーまたはキー組み合わせを継続して長押し",
            ["KeyHolder_PipelineTitle"] = "キーパイプラインシーケンス",
            ["KeyHolder_PipelineHint"] = "• 下のキーボードから任意のステップのキー設定を編集",
            ["KeyHolder_RepeatTitle"] = "繰り返し回数：",
            ["KeyHolder_AddStepBtn"] = "シーケンスにステップを追加",
            ["KeyHolder_VkTitle"] = "仮想キーボードコントローラー",
            ["KeyHolder_CaptureBtn"] = "実キー取得",
            ["KeyHolder_CaptureListening"] = "待機中...",
            ["KeyHolder_CaptureHint"] = "キーボードの任意のキーを押してください...",
            ["KeyHolder_CaptureCanceled"] = "キー取得がキャンセルされました",
            ["KeyHolder_CaptureSuccess"] = "キーを取得しました：{0} (ステップ #{1})",
            ["KeyHolder_ClearKeysBtn"] = "キー消去",
            ["KeyHolder_Step"] = "ステップ #{0}",
            ["KeyHolder_TapKeysBelow"] = "(下のキーを押す)",
            ["KeyHolder_HoldUntilStopped"] = "停止するまでホールド",
            ["KeyHolder_HoldForSeconds"] = "長押し時間 (秒)：",
            ["KeyHolder_RestSeconds"] = "待機時間 (秒)：",
            ["KeyHolder_MoveUp"] = "ステップを上に移動",
            ["KeyHolder_MoveDown"] = "ステップを下に移動",
            ["KeyHolder_DeleteStep"] = "ステップを削除",
            ["KeyHolder_ActionStart"] = "ホールド開始 (F7)",
            ["KeyHolder_ValidationNoKeys"] = "シーケンスのキーの組み合わせを設定してください",
            ["KeyHolder_EditingStep"] = "(編集中 ステップ #{0}: [{1}])",
            ["KeyHolder_NoKeysSet"] = "キー未設定",
            ["KeyHolder_KeysClearedForStep"] = "ステップ #{0} のキーをクリアしました",
            ["KeyHolder_PreflightNoKey"] = "ホールドするキーを入力してください",
            ["KeyHolder_HoldingDuration"] = "{0}[{1}] をホールド中 ({2:F1}s / {3:F1}s)...",
            ["KeyHolder_HoldingContinuously"] = "{0}[{1}] を継続ホールド中 (停止またはF10で解除)...",
            ["KeyHolder_RestingDuration"] = "{0}待機中 ({1:F1}s / {2:F1}s)...",
            ["KeyHolder_LoopPrefix"] = "[ループ {0}/{1}] ",
            ["KeyHolder_LoopInfinitePrefix"] = "[ループ {0}/∞] ",
            ["KeyHolder_StepPrefix"] = "ステップ {0}/{1}：",

            // Clicker Panel
            ["Clicker_Title"] = "連打ツール",
            ["Clicker_Desc"] = "高精度なマウス自動クリックおよびキーボード連打ツール",
            ["Clicker_TargetTypeLabel"] = "対象タイプ：",
            ["Clicker_TargetMouse"] = "🖱️ マウスクリック",
            ["Clicker_TargetKeyboard"] = "⌨️ キーボード連打",
            ["Clicker_TriggerModeLabel"] = "トリガー挙動：",
            ["Clicker_TriggerToggle"] = "トグル (押して開始/停止)",
            ["Clicker_TriggerHold"] = "押しっぱなし連打 (F6 長押し)",
            ["Clicker_HoldModeHint"] = "💡 ホットキーを押している間連打し、離すと停止",
            ["Clicker_MouseButtonLabel"] = "マウスボタン：",
            ["Clicker_MouseLeft"] = "左クリック",
            ["Clicker_MouseRight"] = "右クリック",
            ["Clicker_MouseMiddle"] = "中クリック",
            ["Clicker_SpamKeyLabel"] = "連打するキー：",
            ["Clicker_SpamKeyPlaceholder"] = "連打するキー (例：space, f, 1, e)",
            ["Clicker_IntervalLabel"] = "間隔 (秒)：",
            ["Clicker_CountLabel"] = "クリック回数 (0 = 無限)：",
            ["Clicker_TargetCoordsLabel"] = "クリック座標：",
            ["Clicker_PickCoordBtn"] = "座標取得",
            ["Clicker_ClearCoordBtn"] = "クリア",
            ["Clicker_ShowMarkerCheck"] = "画面上に十字ターゲットを表示",
            ["Clicker_TimeJitterLabel"] = "時間ゆらぎ (±%)：",
            ["Clicker_TimeJitterCheck"] = "間隔をランダム化",
            ["Clicker_LocationJitterLabel"] = "座標ゆらぎ (±px)：",
            ["Clicker_LocationJitterHint"] = "半径ピクセル (0 = 正確な位置)",
            ["Clicker_ActionStart"] = "クリック開始 (F6)",
            ["Clicker_ValidationSpamKey"] = "連打するキーを入力してください",
            ["Clicker_PickingCoordsStatus"] = "マウスを対象へ移動。Space/Enterまたはクリックで決定 (Esc でキャンセル)...",
            ["Clicker_PickCoordsCanceled"] = "座標取得がキャンセルされました",
            ["Clicker_PickCoordsLocked"] = "ターゲット座標を固定しました：({0}, {1})",
            ["Clicker_CoordsCleared"] = "座標をクリアしました (現在のカーソル位置でクリック)",
            ["Clicker_ClickingCount"] = "クリック中 {0}/{1}...",
            ["Clicker_ClickingInfinite"] = "クリック回数：{0} (無制限)...",
            ["Clicker_SpammingKey"] = "[{0}] を連打中 {1}/{2}...",
            ["Clicker_SpammingKeyInfinite"] = "[{0}] を連打中 回数：{1} (無制限)...",

            // Macro Panel
            ["Macro_Title"] = "動作記録と再生",
            ["Macro_Desc"] = "キーボードとマウス操作を記録し、指定した速度で忠実に再生",
            ["Macro_RecordBtn"] = "記録開始 (F9)",
            ["Macro_StopRecordBtn"] = "記録停止",
            ["Macro_ClearBtn"] = "動作クリア",
            ["Macro_RepeatLabel"] = "再生回数 (0 = 無限)：",
            ["Macro_SpeedLabel"] = "再生速度倍率：",
            ["Macro_RecordedActionsTitle"] = "記録された動作 (ダブルクリックで編集)：",
            ["Macro_EditStepBtn"] = "ステップ編集",
            ["Macro_DeleteStepBtn"] = "ステップ削除",
            ["Macro_ActionsCount"] = "{0} 件の動作を記録済み",
            ["Macro_NoActions"] = "まだ動作が記録されていません",
            ["Macro_RecordingStatus"] = "動作を記録中... 操作を行うと自動で記録されます",
            ["Macro_RecordingCountStatus"] = "動作を記録中... {0} 件の動作を記録 (停止をクリックで完了)",
            ["Macro_ClearedStatus"] = "動作をクリアしました",
            ["Macro_ActionReplay"] = "動作再生 (F9)",
            ["Macro_ValidationNoActions"] = "再生する動作がありません。先に記録を行ってください。",
            ["Macro_SelectStepToEdit"] = "編集するステップを選択してください。",
            ["Macro_SelectStepToDelete"] = "削除するステップを選択してください。",
            ["Macro_StepDeleted"] = "ステップ #{0} を削除しました",
            ["Macro_StepUpdated"] = "ステップ #{0} を更新しました",
            ["Macro_ReplayingProgress"] = "動作再生中：ループ {0}、アクション {1}/{2}",
            ["Macro_DetailClickLeft"] = "🖱️ 左クリック ({0}, {1})",
            ["Macro_DetailClickRight"] = "🖱️ 右クリック ({0}, {1})",
            ["Macro_DetailClickMiddle"] = "🖱️ 中クリック ({0}, {1})",
            ["Macro_DetailMouseMove"] = "↗️ カーソル移動 ({0}, {1})",
            ["Macro_DetailKeyDown"] = "⌨️ キー押下 [{0}]",
            ["Macro_DetailKeyUp"] = "⌨️ キー解放 [{0}]",
            ["Macro_DetailTypeText"] = "🔤 文字入力 [{0}]",
            ["Macro_DialogTitle"] = "ステップ #{0} の編集",
            ["Macro_ActionTypeHeader"] = "アクション種類：",
            ["Macro_DelayHeader"] = "実行前遅延 (ミリ秒)：",
            ["Macro_XCoordHeader"] = "X 座標：",
            ["Macro_YCoordHeader"] = "Y 座標：",
            ["Macro_DataHeader"] = "キー名 / テキスト内容：",
            ["Macro_ActionTypeLeftClick"] = "左クリック",
            ["Macro_ActionTypeRightClick"] = "右クリック",
            ["Macro_ActionTypeMiddleClick"] = "中クリック",
            ["Macro_ActionTypeMouseMove"] = "カーソル移動",
            ["Macro_ActionTypeKeyDown"] = "キー押下",
            ["Macro_ActionTypeKeyUp"] = "キー解放",
            ["Macro_ActionTypeTypeText"] = "文字入力",

            // Settings Panel
            ["Settings_Title"] = "設定",
            ["Settings_Desc"] = "環境設定、グローバルホットキー、タスクトレイ設定および外観",
            ["Settings_LangTitle"] = "表示言語",
            ["Settings_LangDesc"] = "Tapsterのインターフェース表示言語を変更します（即時反映）",
            ["Settings_BootTitle"] = "Windows 起動時に自動実行",
            ["Settings_BootDesc"] = "Windows ログイン時にバックグラウンドで自動起動します",
            ["Settings_StartMinimizedTitle"] = "起動時にトレイへ最小化",
            ["Settings_StartMinimizedDesc"] = "メインウィンドウを表示せず、タスクトレイに格納した状態で起動します",
            ["Settings_CloseToTrayTitle"] = "閉じるボタンでトレイへ最小化",
            ["Settings_CloseToTrayDesc"] = "右上の [×] を押した際にアプリを終了せずトレイへ格納します",
            ["Settings_AlwaysOnTopTitle"] = "常に最前面に表示",
            ["Settings_AlwaysOnTopDesc"] = "Tapsterのウィンドウを他のウィンドウより前面に固定します (ホットキー: Ctrl+Alt+T)",
            ["Settings_HotkeysTitle"] = "グローバルホットキー",
            ["Settings_HotkeysDesc"] = "フルスクリーンゲームや作業中でもホットキーから即座に操作できます",
            ["Settings_HkWake"] = "ウィンドウの表示 / 非表示",
            ["Settings_HkClicker"] = "連打の切り替え",
            ["Settings_HkHolder"] = "長押しの切り替え",
            ["Settings_HkTyper"] = "タイピング開始",
            ["Settings_HkMacro"] = "動作再生",
            ["Settings_HkPanicKill"] = "緊急停止 (すべての動作を終了)",
            ["Settings_HkPanicEscape"] = "緊急脱出 (Esc)",
            ["Settings_AboutNavTitle"] = "バージョンと詳細情報",
            ["Settings_AboutNavBtn"] = "詳細を表示",

            // About Panel
            ["About_Title"] = "Tapster について",
            ["About_Desc"] = "アプリケーションバージョン、技術仕様、オープンソース情報",
            ["About_HeroSub"] = "Windows 11 ネイティブ超軽量自動化ユーティリティ",
            ["About_HeroSub2"] = "リモートデスクトップ、仮想マシン、高速連打、ゲーム放置に最適化",
            ["About_SpecsTitle"] = "技術仕様",
            ["About_SpecsUiLabel"] = "UI フレームワーク",
            ["About_SpecsCoreLabel"] = "自動化コア",
            ["About_SpecsCoreValue"] = "Win32 SendInput コア / マイクロ秒精度ディスパッチ",
            ["About_SpecsPublishLabel"] = "配布形式",
            ["About_SpecsPublishValue"] = "二重形式：Microsoft Store MSIX + ポータブル単一EXE",
            ["About_SpecsLicenseLabel"] = "ライセンス",
            ["About_SpecsLicenseValue"] = "MIT License (完全無料＆オープンソース)",
            ["About_PrivacyTitle"] = "プライバシーとローカル設定",
            ["About_PrivacyDesc"] = "100% オフライン実行、テレメトリ送信なし、キーや個人情報を一切収集しません",
            ["About_OpenFolderBtn"] = "設定フォルダーを開く",
        },

        [LangZhCn] = new(StringComparer.OrdinalIgnoreCase)
        {
            // Navigation
            ["Nav_Typer"] = "打字",
            ["Nav_Holder"] = "长按",
            ["Nav_Clicker"] = "连点",
            ["Nav_Macro"] = "重放",
            ["Nav_About"] = "关于",
            ["Nav_Settings"] = "设置",

            // Tray Menu
            ["Tray_ShowHide"] = "显示 / 隐藏 Tapster",
            ["Tray_AlwaysOnTop"] = "窗口置顶",
            ["Tray_Exit"] = "退出 Tapster",
            ["Tray_Tooltip"] = "Tapster (Ctrl+Alt+T 唤醒)",

            // Common Actions & Status
            ["Common_Ready"] = "就绪",
            ["Common_Running"] = "运行中...",
            ["Common_StartingIn"] = "{0} 秒后启动... 请切换至目标程序！",
            ["Common_Stop"] = "停止",
            ["Common_Start"] = "开始",
            ["Common_Delay"] = "延迟 (秒)：",
            ["Common_Finished"] = "运行完成",
            ["Common_StoppedByUser"] = "用户已手动停止",
            ["Common_TaskCanceled"] = "任务已取消",
            ["Common_EmergencyStop"] = "已通过 F10 紧急热键终止所有任务",
            ["Common_SwitchedTask"] = "已从 {0} 切换任务",
            ["Common_Error"] = "错误：{0}",
            ["Common_Save"] = "保存",
            ["Common_Cancel"] = "取消",

            // Typer Panel
            ["Typer_Title"] = "自动打字机",
            ["Typer_Desc"] = "自动模拟键盘输入预设文本或代码，支持远程桌面与终端",
            ["Typer_TargetText"] = "目标文本：",
            ["Typer_PasteBtn"] = "粘贴",
            ["Typer_ClearBtn"] = "清空",
            ["Typer_TextPlaceholder"] = "在此输入要自动输入的文本内容...",
            ["Typer_ModeLabel"] = "输入模式：",
            ["Typer_ModeKeystroke"] = "⌨️ 逐字键盘模拟",
            ["Typer_ModeClipboard"] = "📋 剪贴板粘贴 (瞬间)",
            ["Typer_ClipboardHint"] = "⚡ 瞬间粘贴 (Ctrl+V) 并自动恢复剪贴板原始内容",
            ["Typer_TrailingKeyLabel"] = "尾随按键：",
            ["Typer_TrailingNone"] = "无",
            ["Typer_TrailingEnter"] = "Enter (发送 / 换行)",
            ["Typer_TrailingTab"] = "Tab (切换栏位)",
            ["Typer_IntervalLabel"] = "按键间隔 (秒/字)：",
            ["Typer_JitterCheck"] = "自然打字微幅抖动 (±15%)",
            ["Typer_HistoryTitle"] = "输入记录",
            ["Typer_ActionStart"] = "开始打字 (F8)",
            ["Typer_ValidationEmpty"] = "请输入要打字的文本内容",
            ["Typer_PastingClipboard"] = "正在通过剪贴板粘贴 {0} 个字符...",
            ["Typer_PastedClipboard"] = "已粘贴 {0} 个字符",
            ["Typer_TypingChar"] = "正在输入第 {0}/{1} 个字符...",
            ["Typer_PasteError"] = "粘贴错误：{0}",

            // Key Holder Panel
            ["KeyHolder_Title"] = "按键长按",
            ["KeyHolder_Desc"] = "连续长按指定按键或组合键，支持奔跑、蓄力与按键模拟",
            ["KeyHolder_PipelineTitle"] = "按键流水线序列",
            ["KeyHolder_PipelineHint"] = "• 点击任意步骤，通过下方键盘自定义按键组合",
            ["KeyHolder_RepeatTitle"] = "循环次数：",
            ["KeyHolder_AddStepBtn"] = "添加步骤至序列",
            ["KeyHolder_VkTitle"] = "虚拟键盘控制器",
            ["KeyHolder_CaptureBtn"] = "捕获实体按键",
            ["KeyHolder_CaptureListening"] = "监听中...",
            ["KeyHolder_CaptureHint"] = "请按下键盘上的任意按键...",
            ["KeyHolder_CaptureCanceled"] = "按键捕获已取消",
            ["KeyHolder_CaptureSuccess"] = "已捕获按键：{0} (步骤 #{1})",
            ["KeyHolder_ClearKeysBtn"] = "清空按键",
            ["KeyHolder_Step"] = "步骤 #{0}",
            ["KeyHolder_TapKeysBelow"] = "(点击下方按键)",
            ["KeyHolder_HoldUntilStopped"] = "长按至停止",
            ["KeyHolder_HoldForSeconds"] = "长按 (秒)：",
            ["KeyHolder_RestSeconds"] = "休息 (秒)：",
            ["KeyHolder_MoveUp"] = "上移步骤",
            ["KeyHolder_MoveDown"] = "下移步骤",
            ["KeyHolder_DeleteStep"] = "删除步骤",
            ["KeyHolder_ActionStart"] = "开始长按 (F7)",
            ["KeyHolder_ValidationNoKeys"] = "请为序列中的步骤配置至少一个按键组合",
            ["KeyHolder_EditingStep"] = "(正在编辑步骤 #{0}: [{1}])",
            ["KeyHolder_NoKeysSet"] = "未设置按键",
            ["KeyHolder_KeysClearedForStep"] = "已清除步骤 #{0} 的按键",
            ["KeyHolder_PreflightNoKey"] = "请设置要长按的按键",
            ["KeyHolder_HoldingDuration"] = "{0}长按 [{1}] ({2:F1}s / {3:F1}s)...",
            ["KeyHolder_HoldingContinuously"] = "{0}持续长按 [{1}] (按停止或 F10 释放)...",
            ["KeyHolder_RestingDuration"] = "{0}休息中 ({1:F1}s / {2:F1}s)...",
            ["KeyHolder_LoopPrefix"] = "[第 {0}/{1} 轮] ",
            ["KeyHolder_LoopInfinitePrefix"] = "[第 {0}/∞ 轮] ",
            ["KeyHolder_StepPrefix"] = "步骤 {0}/{1}：",

            // Clicker Panel
            ["Clicker_Title"] = "鼠标连点与按键连打",
            ["Clicker_Desc"] = "高精度定时鼠标连点、指定坐标锁定与键盘连打工具",
            ["Clicker_TargetTypeLabel"] = "连打目标：",
            ["Clicker_TargetMouse"] = "🖱️ 鼠标连点",
            ["Clicker_TargetKeyboard"] = "⌨️ 键盘连打",
            ["Clicker_TriggerModeLabel"] = "触发行为：",
            ["Clicker_TriggerToggle"] = "开关切换 (按一下开始/停止)",
            ["Clicker_TriggerHold"] = "按住连打 (按住 F6 连打)",
            ["Clicker_HoldModeHint"] = "💡 按住热键持续连打，松开即刻停止",
            ["Clicker_MouseButtonLabel"] = "点击按钮：",
            ["Clicker_MouseLeft"] = "左键",
            ["Clicker_MouseRight"] = "右键",
            ["Clicker_MouseMiddle"] = "中键",
            ["Clicker_SpamKeyLabel"] = "连打按键：",
            ["Clicker_SpamKeyPlaceholder"] = "输入要连打的按键 (例：space, f, 1)",
            ["Clicker_IntervalLabel"] = "间隔 (秒)：",
            ["Clicker_CountLabel"] = "连击次数 (0 = 无限)：",
            ["Clicker_TargetCoordsLabel"] = "目标坐标：",
            ["Clicker_PickCoordBtn"] = "锁定坐标",
            ["Clicker_ClearCoordBtn"] = "清空",
            ["Clicker_ShowMarkerCheck"] = "在屏幕上显示准星标记",
            ["Clicker_TimeJitterLabel"] = "时间随机抖动 (±%)：",
            ["Clicker_TimeJitterCheck"] = "随机间隔",
            ["Clicker_LocationJitterLabel"] = "位置随机抖动 (±px)：",
            ["Clicker_LocationJitterHint"] = "像素半径 (0 = 锁定精确点)",
            ["Clicker_ActionStart"] = "开始点击 (F6)",
            ["Clicker_ValidationSpamKey"] = "请输入要连打的按键名称",
            ["Clicker_PickingCoordsStatus"] = "移动鼠标至目标位置。按空格/Enter或点击以锁定 (Esc 取消)...",
            ["Clicker_PickCoordsCanceled"] = "坐标选取已取消",
            ["Clicker_PickCoordsLocked"] = "已锁定目标坐标：({0}, {1})",
            ["Clicker_CoordsCleared"] = "已清除坐标 (在当前光标位置点击)",
            ["Clicker_ClickingCount"] = "点击中 {0}/{1}...",
            ["Clicker_ClickingInfinite"] = "点击次数：{0} (无限)...",
            ["Clicker_SpammingKey"] = "连打中 [{0}] {1}/{2}...",
            ["Clicker_SpammingKeyInfinite"] = "连打中 [{0}] 次数：{1} (无限)...",

            // Macro Panel
            ["Macro_Title"] = "动作录制与重放",
            ["Macro_Desc"] = "录制鼠标点击与键盘按键动作，并自定义速度重放",
            ["Macro_RecordBtn"] = "开始录制 (F9)",
            ["Macro_StopRecordBtn"] = "停止录制",
            ["Macro_ClearBtn"] = "清除动作",
            ["Macro_RepeatLabel"] = "重放次数 (0 = 无限)：",
            ["Macro_SpeedLabel"] = "重放速度倍率：",
            ["Macro_RecordedActionsTitle"] = "已录制动作 (双击步骤可编辑)：",
            ["Macro_EditStepBtn"] = "编辑步骤",
            ["Macro_DeleteStepBtn"] = "删除步骤",
            ["Macro_ActionsCount"] = "已录制 {0} 个动作",
            ["Macro_NoActions"] = "尚未录制任何动作",
            ["Macro_RecordingStatus"] = "正在录制动作... 点击或输入任何内容以进行记录",
            ["Macro_RecordingCountStatus"] = "正在录制动作... 已捕获 {0} 个动作 (点击停止以完成)",
            ["Macro_ClearedStatus"] = "动作已清除",
            ["Macro_ActionReplay"] = "重放动作 (F9)",
            ["Macro_ValidationNoActions"] = "尚未录制任何动作！请先录制动作。",
            ["Macro_SelectStepToEdit"] = "请先选择要编辑的步骤。",
            ["Macro_SelectStepToDelete"] = "请先选择要删除的步骤。",
            ["Macro_StepDeleted"] = "已删除步骤 #{0}",
            ["Macro_StepUpdated"] = "已更新步骤 #{0}",
            ["Macro_ReplayingProgress"] = "重放动作中：第 {0} 轮，动作 {1}/{2}",
            ["Macro_DetailClickLeft"] = "🖱️ 左键点击 ({0}, {1})",
            ["Macro_DetailClickRight"] = "🖱️ 右键点击 ({0}, {1})",
            ["Macro_DetailClickMiddle"] = "🖱️ 中键点击 ({0}, {1})",
            ["Macro_DetailMouseMove"] = "↗️ 移动光标至 ({0}, {1})",
            ["Macro_DetailKeyDown"] = "⌨️ 按下按键 [{0}]",
            ["Macro_DetailKeyUp"] = "⌨️ 松开按键 [{0}]",
            ["Macro_DetailTypeText"] = "🔤 输入文本 [{0}]",
            ["Macro_DialogTitle"] = "编辑步骤 #{0}",
            ["Macro_ActionTypeHeader"] = "动作类型：",
            ["Macro_DelayHeader"] = "执行前延迟 (毫秒)：",
            ["Macro_XCoordHeader"] = "X 坐标：",
            ["Macro_YCoordHeader"] = "Y 坐标：",
            ["Macro_DataHeader"] = "按键名称 / 文本内容：",
            ["Macro_ActionTypeLeftClick"] = "左键点击",
            ["Macro_ActionTypeRightClick"] = "右键点击",
            ["Macro_ActionTypeMiddleClick"] = "中键点击",
            ["Macro_ActionTypeMouseMove"] = "移动光标",
            ["Macro_ActionTypeKeyDown"] = "按下按键",
            ["Macro_ActionTypeKeyUp"] = "松开按键",
            ["Macro_ActionTypeTypeText"] = "输入文本",

            // Settings Panel
            ["Settings_Title"] = "设置",
            ["Settings_Desc"] = "首选项、全局热键、系统托盘与外观设置",
            ["Settings_LangTitle"] = "界面语言",
            ["Settings_LangDesc"] = "选择 Tapster 界面显示语言，支持即时生效",
            ["Settings_BootTitle"] = "开机自启动",
            ["Settings_BootDesc"] = "登录 Windows 时在后台自动启动 Tapster 并常驻于系统托盘",
            ["Settings_StartMinimizedTitle"] = "启动时最小化至托盘",
            ["Settings_StartMinimizedDesc"] = "程序启动时不显示主窗口，直接隐藏至托盘",
            ["Settings_CloseToTrayTitle"] = "关闭时最小化至托盘",
            ["Settings_CloseToTrayDesc"] = "点击右上角关闭按钮时最小化至托盘，保持全局快捷键随时可用",
            ["Settings_AlwaysOnTopTitle"] = "窗口置顶",
            ["Settings_AlwaysOnTopDesc"] = "将 Tapster 窗口固定在其他应用程序顶层 (全局热键: Ctrl+Alt+T)",
            ["Settings_HotkeysTitle"] = "全局功能热键",
            ["Settings_HotkeysDesc"] = "在任何全屏游戏或程序中均可直接通过热键操作",
            ["Settings_HkWake"] = "唤醒 / 隐藏主窗口",
            ["Settings_HkClicker"] = "切换连点",
            ["Settings_HkHolder"] = "切换长按",
            ["Settings_HkTyper"] = "启动打字",
            ["Settings_HkMacro"] = "重放动作",
            ["Settings_HkPanicKill"] = "紧急全部终止",
            ["Settings_HkPanicEscape"] = "紧急中断跳出",
            ["Settings_AboutNavTitle"] = "版本与项目信息",
            ["Settings_AboutNavBtn"] = "查看详情",

            // About Panel
            ["About_Title"] = "关于 Tapster",
            ["About_Desc"] = "应用程序版本、技术规格、开源协议与项目链接",
            ["About_HeroSub"] = "Windows 11 原生超轻量自动化助手",
            ["About_HeroSub2"] = "专为远程桌面 (VNC/RDP)、虚拟机、游戏挂机与高频点击量身打造",
            ["About_SpecsTitle"] = "技术规格",
            ["About_SpecsUiLabel"] = "UI 框架",
            ["About_SpecsCoreLabel"] = "底层自动化核心",
            ["About_SpecsCoreValue"] = "Win32 SendInput 核心 / 微秒级高精调度",
            ["About_SpecsPublishLabel"] = "分发形式",
            ["About_SpecsPublishValue"] = "双轨制：Microsoft Store MSIX 封装 + Standalone 绿色纯单文件 EXE",
            ["About_SpecsLicenseLabel"] = "开源协议",
            ["About_SpecsLicenseValue"] = "MIT License (100% 免费开源)",
            ["About_PrivacyTitle"] = "隐私承诺与本地设置",
            ["About_PrivacyDesc"] = "100% 离线纯本地运行，零网络遥测传输，不收集任何按键或个人资料",
            ["About_OpenFolderBtn"] = "打开设置目录",
        }
    };
}
